# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install behave
        python -m pip install allure-behave
        python -m pip install mock
        python -m pip install numpy
    - name: Run tests with behave
      run: |
        python -m behave -f allure_behave.formatter:AllureFormatter -o report ./features
    - name: Install Allure
      run: |
        sudo apt-get update 
        sudo apt-get install allure
    - uses: simple-elf/allure-report-action@master
      if: always()
      id: allure-report
      continue-on-error: true
      with:
        allure_results: report
        gh_pages: gh-pages
        allure_report: allure-report
        allure_history: allure-history


